### PR TITLE
[tree-filter] Make search case insensitve and accept RegExp

### PR DESCRIPTION
**Pull request by wikiped**
Currently filtering entries in the file tree is Case Sensitive. This patch will make it case insensitive and it will also accept Regular Expressions as valid search strings.

### CODE REVIEW

**Comment by jcb91** [comment]
I think there's an issue requesting case sensitivity on the upstream repo https://github.com/jdfreder/tree-filter so it might be worth adding this there too? It'd also be good to either make regex optional, or at least a little more obvious that it's happening (e.g. readme, tooltips)

**Comment by juhasch** [comment]
I think making the regex configurable sounds good.

**Comment by wikiped** [comment]
[The patch](https://github.com/wikiped/jupyter_contrib_nbextensions/pull/2) was added to make case sensitivity / RegExp optional.

**Comment by juhasch** [comment]
Thanks @jcb91

**Pull request merged**
