### PR TITLE
[kernel_exec_on_cells] make shift-click on button autoformat all cells

### PR DESCRIPTION
**Pull request by jcb91**
as discussed in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1202#issuecomment-359263483

### CODE REVIEW

**Comment by jcb91** [comment]
actually, it might make more sense to open this PR in the upstream, then merge that back here...

**Comment by jfbercher** [comment]
Checked the code: very nice :+1:

**Comment by jcb91** [comment]
closing this in favour of https://github.com/jfbercher/code_prettify/pull/10, will pull that in later

**Comment by jcb91** [comment]
@jfbercher thanks :smile:

**Pull request closed without merging**
