### PR TITLE
yapf code autoformatter/prettifier extension

### PR DESCRIPTION
**Pull request by jfbercher**
Triggered by a remark by @mraxilus in #365  I attempted a little extension to autoformat/prettify Python code in a notebook's code cell.  It uses the Yapf python package to format the code. 
Of course, the extension is **not** kernel agnostic, but seems to do the work... I let the maintainers here decide if it can be added to the repo. 

It was an interesting exercise to learn how to implement bi-directional communication between javascript and the Jupyter kernel. Other kernels may be added in the future (eg R with AutoformatR).  As usual, Suggestions, corrections are welcome. In the hope it will be useful. 

This extension uses the [YAPF](https://github.com/google/yapf) Python module to reformat IPython code cells. 
**Of course, you must have `YAPF` package available somewhere in your Python path; ** 
Install via `pip install yapf [--user]`. 
 
Then the extension provides
- a toolbar button
- a keyboard shortcut (default: Ctrl-L)
for reformatting the current code-cell. 
Syntax shall be correct. The extension will point basic syntax errors, see demo. 
demo

Of course, this extension is *not* language agnostic... However, this first attempt may be the basis for a more general "code prettyfier" extension.

Installation
------------

If you use [jupyter-contrib-nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions), proceed as usual. 

Otherwise, you can still install/try the extension from my personal repo, using
```
jupyter nbextension install https://github.com/jfbercher/yapf_ext/archive/master.zip --user
jupyter nbextension enable yapf_ext-master/yapf_ext
```

History: 
---------
@jfbercher, august 14, 2016, first version.

### CODE REVIEW

**Comment by juhasch** [comment]
Nice!

**Comment by mraxilus** [comment]
Wow, definitely what I was looking for. Great job.

**Comment by juhasch** [comment]
Let's merge.

**Comment by janschulz** [comment]
> It was an interesting exercise to learn how to implement bi-directional communication between javascript and the Jupyter kernel. Other kernels may be added in the future (eg R with AutoformatR). As usual, Suggestions, corrections are welcome. In the hope it will be useful.

Are the widget "comm" channels a way to do it? I never really looked at them, but my sketchy understanding is that they are a way to let UI communicate with the kernel and get results back.

**Comment by jfbercher** [comment]
@janschulz  I did not use the comm manager (but will investigate - thanks for the link). I simply used the fact that one can specify a callback on the output of  `kernel.execute()` on the iopub channel; as in 
```
Jupyter.notebook.kernel.execute(code_input, { iopub: { output: code_exec_callback } }, { silent: false });
```
I have a prettifier for R  which works and look for javascript (via js-beautify). Then I will include both.

**Comment by mraxilus** [comment]
One issue I found is that it seems to fail on docstrings. 
For example trying to run the extension on a cell like this:

```python
def test():
    """This is a docstring."""
    pass
```

Fails with this error message:
selection_006

I'm not sure if it's just my setup. 
Let me know if you experience it as well.

**Comment by jfbercher** [comment]
@mraxilus I see the problem. This is a problem of quotes in strings. I embedded the text returned by `cell.get_text` in triple quotes. Thus need to escape/replace the (triple) quotes inside. 
I will update shortly.

**Comment by jfbercher** [comment]
Updated in #726

**Comment by ericgtaylor** [comment]
Hi, I'm using the YAPF python formatter extension, and I'm getting this bug where YAPF (or something) inserts a quote at the beginning of my cell. Any idea why this is happening? Thanks!
screen shot 2017-01-23 at 9 51 19 am

**Comment by jfbercher** [comment]
Yes, this was an issue in a previous version of the extension. The `yapf_ext` (don't remember the exact name) was deprecated in favor of the `code prettifier` #726 extension, which we have largely reworked and improved recently #837. 
Please try to update your nbextensions and select the new code_prettify extension. If the bug still exists, we will try to address it of course.

**Pull request merged**
