### PR TITLE
Make sure gutter is loaded before initializing it.

### PR DESCRIPTION
**Pull request by juhasch**
Overlooked that at #897.

### CODE REVIEW

**Comment by jcb91** [comment]
Is this necessary? The define should only execute once the addon's been loaded anyway, no?

**Comment by juhasch** [comment]
Unfortunately yes. Without, it looks like this:
bildschirmfoto 2017-02-20 um 22 31 03

**Comment by jcb91** [comment]
ok, that's strange!

I think it must be more of a timing problem though, since the `define([` call is analogous to the `require([` one in terms of loading order, so if anything it should load the addon _earlier_. But whatever, if this fixes it for now, it's not worth worrying about :smile:

**Comment by juhasch** [comment]
It is a timing problem, and this is the least ugly hack I could come up with.
The gutter stuff can be strange...
If you have an idea what to do about it, you're welcome. But don't waste your time on it.

**Comment by jcb91** [comment]
> The gutter stuff can be strange...

No kidding!

> If you have an idea what to do about it, you're welcome. But don't waste your time on it.

Yeah, it looks too complicated to quickly think about, so if this ides fixes it for now, I think you've got the right plan here!

**Pull request merged**
