### PR TITLE
[toc2] configurable titles; dialog-alterable metadata settings

### LINKED ISSUE #1098: EXT: TOC title customization
I use this extension a lot and it is great! I am trying to replace the "Table of Contents" text with a text that would match the language of the text. Having an English title while the rest of the document is not English does not look nice:)

### PR DESCRIPTION
**Pull request by jcb91**
* fixes #1098 by adding titles which can be customised
 * adds a dialog to edit settings in notebook metadata, which should hopefully avoid confusion as in ~#1070~, #1088

### CODE REVIEW

**Comment by jfbercher** [comment]
Very nice and very useful; Thanks @jcb91 !

I just tried it. A couple of remarks:

-  It would be great if modifications to the toc cell title/sidebar title were taken into account immediately (for now it seems that one needs to save and reload, though the notebook metadata are correctly updated and even when reloading via the reload button)
- perhaps that these two parameters can be also added system wise in the yaml config file 
- I think the reload button is, for a moment, mostly useless, since toc is updated every time a md cell is rendered

**Comment by jfbercher** [comment]
A small not really important issue. 
Begin with toc2 as a sidebar. Drag it as a floating window. Then collapse it. Drag it back to the sidebar. Then uncollapse it. It doesn't show up. It seems that the height is zero. Drag it back as a floating widow, and try to collape/uncollapse; the height seems still zero. One must resize the window to get the toc contents. 

Sorry I am really overloaded and don't really have time to look in the code;

**Comment by jcb91** [comment]
Thanks for taking time to look @jfbercher,much appreciated :)

> It would be great if modifications to the toc cell title/sidebar title were taken into account immediately

Ok, good spot. I have more modifications locally which aren't in this pr (mainly for simplicity/clarity of each pr), so I thought this was already the case, but at any rate, it should be easy to make it so.

> perhaps that these two parameters can be also added system wise in the yaml config file

Good point, I'd forgotten this!

> I think the reload button is, for a moment, mostly useless

True, I just figured it was easier to keep than try to catch every edge case for when to update - would you rather remove it completely?

> perhaps that the collapse/uncollapse button should be desactivated/grayed when the toc window is transformed into the sidebar, and the toc automatically shown/uncollapsed

That's the obvious/intuitive behaviour for me, but I wasn't sure whether others were using it as both sidebar and collapsed, so kept it. I can easily adjust it to work this way though, if you think that's ok?

**Comment by jcb91** [comment]
> Sorry I am really overloaded and don't really have time to look in the code

No problem, thanks for looking at all! Bonne chance with all the other stuff :)

**Comment by jfbercher** [comment]
>>I think the reload button is, for a moment, mostly useless

>True, I just figured it was easier to keep than try to catch every edge case for when to update - would you rather remove it completely?

>> perhaps that the collapse/uncollapse button should be desactivated/grayed when the toc window is transformed into the sidebar, and the toc automatically shown/uncollapsed

I don't see any problem to remove it, but perhaps in another PR, indeed. 

> That's the obvious/intuitive behaviour for me, but I wasn't sure whether others were using it as both sidebar and collapsed, so kept it. I can easily adjust it to work this way though, if you think that's ok?

yes, I think it is something to do. 

>> Sorry I am really overloaded and don't really have time to look in the code

> No problem, thanks for looking at all! Bonne chance with all the other stuff :)

Thanks!

**Comment by jfbercher** [comment]
Perhaps also update the README/history?

**Comment by jcb91** [comment]
Ok, I think this should be working now. Main differences include:

 * The panel is now added to the `#site` div in live notebooks, as it allows much simpler logic for the sidebar - just setting top & bottom rather than height.
 * The minimise button is now hidden in sidebar mode
 * Simplified setting & saving of size & position in metadata
 * add `display: hidden` to `tocSkip` class

**Comment by jfbercher** [comment]
Hi @jcb91 

Just downloaded and begun testing. Very nice! :+1:

**Comment by jfbercher** [comment]
>  Very nice!

No. Great!

**Comment by jcb91** [comment]
:) glad you like it!

**Comment by jankoslavic** [comment]
This looks good; hope it will be merged to master soon! Good job!

**Comment by jcb91** [comment]
Ok, let's merge this, and fix anything it's missed as it turns up :)

**Pull request merged**
