### PR TITLE
Toc2: export 

### PR DESCRIPTION
**Pull request by jfbercher**
- Template toc3.tpl is now useless and is removed
- An exporter has been designed, an entry point added in setup.py. It is now possible to export to html with toc by 
```
jupyter nbconvert --to html_toc FILE.ipynb 
```
You will need to update (reinstall) the package, eg via `pip3 install -e jupyter_contrib_nbextensions --user`

### CODE REVIEW

**Comment by jcb91** [comment]
>  an entry point added in setup.py

this bit doesn't seem to have made it into the PR yet...

**Comment by jfbercher** [comment]
Yes, sorry, it is included in the latex_envs PR

Le 29 juil. 2016 00:45, "Josh Barnes" <notifications@github.com> a écrit :

an entry point added in setup.py

this bit doesn't seem to have made it into the PR yet...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/702#issuecomment-236047496>,
or mute the thread

**Comment by jcb91** [comment]
ok, #703 is now merged, so I think this one can go ahead too.

**Comment by jfbercher** [comment]
Thanks @jcb91

**Pull request merged**
