### PR TITLE
[collapsible_headings] new features!

### PR DESCRIPTION
**Pull request by jcb91**
* unbind event handlers during notebook loading, so collapsing/uncollapsing headings don't slow down the load, as mentioned in #822
* allow left-arrow keyboard shortcut to skip to higher-level headings, for faster navigation
* add support for embedding collapsible_headings into nbconverted html documents, as requested in #605, #847. This is done through use of an exporter model which can be applied more generally through subclassing, though at the moment, the only other example that comes to mind of embedding things in html is toc2.

### CODE REVIEW

**Comment by jcb91** [comment]
I haven't yet updated any of the docs for this...

**Comment by jcb91** [comment]
or tests! d'oh

**Comment by jfbercher** [comment]
:+1: :+1:

**Comment by jcb91** [comment]
Ok, I'm gonna merge this as-is, maybe add support for exporting alongside toc2 in another PR...

**Pull request merged**
