### PR TITLE
FIXES #1224 - Added contribution section to README.md

### LINKED ISSUE #1224: Contributing - Add a section to README.md
I wanted to [make an improvement](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1223), but it took quite a while until I managed to setup a working development environment. A contributing section [like in Jupyterhubs repository](https://github.com/jupyterhub/jupyterhub#contributing) would have helped me!

Perhaps something like this could be added to the readme?

Contributing
============

1. __Fork__
2. __Clone and setup__
```bash
git clone https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
cd jupyter_contrib_nbextensions
pip install --editable .
jupyter-contrib-nbextension install --symlink --sys-prefix
```
3. __Develop__
4. __Pull request__

### PR DESCRIPTION
**Pull request by consideRatio**
Fixes #1224 by providing a section in the README.md on how to setup a development environment.

### CODE REVIEW

**Comment by juhasch** [comment]
Thank you for your contribution. This is a good idea and we were actually discussing this here: #1213.

I think it is better adding a new CONTRIBUTING.md and just add a link in the README.md.
This way it is easier to add new content without making the readme unwieldily large.

Can you change the PR to provide a CONTRIBUTING.md ?
You can also take a look at the Wiki entry here:
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/wiki/Create-a-new-Notebook-Extension

**Comment by consideRatio** [comment]
Thank you for the input @juhasch ! This is now based this on @benelot wiki entry. I added a section on how to setup development and tried to update the text to an audience interested in contributing in some way but not necessarily creating an extension.

---

# Contributing to jupyter notebook nbextensions

We are super happy that you intend to contribute to the nbextensions! You can discuss improvements in issues and improvement them in pull requests.

## Create an issue

Do not hesitate to open up an issue, you can discuss bugs, improvements or new extensions in them. Creating an issue is a good starting point for code contributions. The community can support you with experience of similar extensions, pros and cons, what to look for etc.

Here is an example issue of how @benelot did it that worked pretty smoothly: [#1193](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1193)

## Setup development

1. __Fork and clone__
First fork this repo, then clone your fork. In this way you become prepared to make a pull request.

```shell
# clone your fork
git clone https://github.com/<your-github-username>/jupyter_contrib_nbextensions.git
cd jupyter_contrib_nbextensions
```
2. __Setup__
```shell
# run from the main directory, where setup.py is
pip install --editable .
jupyter-contrib-nbextension install --symlink --sys-prefix
```

## Create an extension

Add a folder with the name of your new extension to [jupyter_contrib_nbextensions/nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions). Check out the [Jupyter Notebook extension structure link](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/internals.html) to know what has to be in that folder and what the general conventions are.

## Create a pull request

As you are ready with your code contribution, make a pull-request to the main repo and briefly explain what you have done.

Here is an example pull request of how @benelot did it that worked super well: [#1213](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1213)

Please also update the [CHANGELOG.md](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/CHANGELOG.md).

**Comment by consideRatio** [comment]
Thank you for the code review @jcb91 !! I'll fix it all!

**Comment by consideRatio** [comment]
@jcb91 done!

Technical detail: I made a rebase on this repo's updated master branch, and then a force push to my fork, making your code review comments dangle as those commits no longer have the same hash. I can't see how it would affect anything other than that though, but my experience is lacking when it comes to this.

**Comment by jcb91** [comment]
Thanks @consideRatio, rebase is fine. I've added a couple more clarification notes about virtual environments, and the possibility of using github for small direct edits of things like docs. Looks good to merge, I think

**Comment by consideRatio** [comment]
Ah nice! This looks good! I did not know about Github edits!

---

__Off topic:__ I was confused by how you have made edits to this PR, and have tried to learn about it by googling and reading.

I'm thinking of questions like:
- Where is this changed PR code stored?
- What would happen if I made additional changes now?

I read the following, but is still confused.
- https://coderwall.com/p/ffacww/editing-incoming-pull-requests
- https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by jcb91** [comment]
>  I was confused by how you have made edits to this PR

It was perhaps a little impolite of me to just push, and it might have been nicer/less confusing to make a PR to your fork from mine. For how it works, I've attempted an outline below:

> I'm thinking of questions like:
>
> Where is this changed PR code stored?
> What would happen if I made additional changes now?

Essentially what's going on here is that I have pushed commits to the [`readme-pr`](https://github.com/consideRatio/jupyter_contrib_nbextensions/tree/readme-pr) branch of _your_ github fork [consideRatio/jupyter_contrib_nbextensions](https://github.com/consideRatio/jupyter_contrib_nbextensions). There's a small suggestion that this is possible near the bottom of the PR page, just above the status box:

> 

Normally, I would not have permission to push to your fork, but [since September 2016](https://github.com/blog/2247-improving-collaboration-with-forks), GitHub PRs provide a setting which allows anyone with push access for the repo to which you're making the PR (in this case, I have push access for [ipython-contrib/jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions)) to push to the PR branch on the fork _from_ which the PR comes (in this case, `readme-pr` on your fork). You can set this when creating a PR:

> 

Or afterwards for PRs you own (opened) - see the tiny checkbox at the bottom of the right-hand side panel:

> 

Also, this [help page](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) gives some more info and links.

So, if you were to make further changes to your local branch, you'd end up having diverged from your github repo. To avoid this, you'd need to either pull changes from your github repo _before_ making further edits locally, or else rebase/merge changes already made locally onto/into the newly-updated github branch, before pushing the updated history up to your fork again. Make sense?

**Comment by consideRatio** [comment]
Wow @jcb91 that made perfect sense, thank you a lot for the effort of explaining this to me, I could get it very very quickly due to this thorough explanation!

**Pull request merged**
