### PR TITLE
[Exercise2] Wait for notebook to be fully loaded before restoring solution states (hidden/dispayed)

### PR DESCRIPTION
**Pull request by jfbercher**
Tentative fix to @#1079 

The main modification is in the `load_ipython_extension()` function where we wait for the notobook to be fully loaded before trigering the (new) `display_existing_sols_at_startup()` function. 

Also I ran a code prettifying on all that. 

@satra, @dkirkby, can you download the new `main.js`, replace the old one in your nbextension/exercise2/ directory and test if it works for you?

### CODE REVIEW

**Comment by dkirkby** [comment]
For the record, my conda env seems to have `exercise2/main.js` in two locations:
```
.../share/jupyter/nbextensions/exercise2/main.js
.../lib/python3.6/site-packages/jupyter_contrib_nbextensions/nbextensions/exercise2/main.js
```
so I will update both of these by hand and will let you know.

**Comment by jcb91** [comment]
> my conda env seems to have `exercise2/main.js` in two locations

This is expected. The first is the one used by the notebook server, the second is the copy in the python package, from which the in-use one gets copied.

**Comment by dkirkby** [comment]
I have been using the updated `main.js` for a few days now and haven't had any issues.  Old notebooks using the extension still work, and I have been able to create new ones also.  I can't really confirm that the issue is fixed since I don't know how to reproduce it, but it sounds like the changes address the problem.

**Comment by satra** [comment]
@djarecka - when you get a chance can you check this out?

**Comment by dkirkby** [comment]
@jcb91 Do you expect this will be a complete fix for this issue?  I got the impression from #1195 that the problem might be deeper.

**Comment by jcb91** [comment]
> @jcb91 Do you expect this will be a complete fix for this issue? I got the impression from #1195 that the problem might be deeper.

Sort of. There are three possibilities:

1. the notebook is small enough that it loads completely before the nbextension loads. In this case, there's no problem, even without the updates
2. the notebook is large enough that the nbextension loads _before_ all the notebook has loaded, in which case any exercises which load _after_ the nbextension loads currently don't get their solutions hidden.
3. the notebook is _so_ large that no nbextensions get loaded at all, because requirejs assumes the calls to fetch them have timed out. This is the deeper issue addressed in #1195, which requires a fix/mitigation in `custom.js` (so that it gets executed before nbextension loading is attempted)

The updates discussed here and in #1206 should fix case two, but don't (can't!) help in case 3. Does that make sense?

**Comment by jcb91** [comment]
Closing this, as it should hopefully be handled (assuming nbextension gets loaded at all, as discussed above) by #1206.

**Comment by djarecka** [comment]
@jcb91 @jfbercher - thank you for your help. Unfortunately, I'm having problem with finding the notebooks that we had problems with loading last summer...
I will remember to report it if I see the problem again.

**Pull request closed without merging**
