### PR TITLE
Feature/table beautifier sortable

### PR DESCRIPTION
**Pull request by jcb91**
replacement for #570 

@janschulz sorry about the errors, I ought to have gone with the route I've used previously for require-ing things which may or may not be available, I've made it more robust now I think...

### CODE REVIEW

**Comment by jcb91** [comment]
(to provide some of #540)

**Comment by jcb91** [comment]
I'm not sure what the 'check' was about though, as it doesn't seem to be in the source.

**Comment by janschulz** [comment]
Ok, this "works", but has teh side effect to remove the last column and replace all valueswithin that colum with `-`:


R Code (needs a master version of all libs):

```R
library("dplyr")
options(jupyter.log_level = 3)
options(jupyter.rich_display = TRUE)
data.frame(a=1:200, b=201:400, c=401:600)
```

**Comment by janschulz** [comment]
When I reload the notebook without the extension activated, all values are there. When I reload the notebook with the extension activated, all values are there. Only when I run the cell will the last column be replaced with '-'

**Comment by jcb91** [comment]
yeah, I think the bootstrap-table extension I tried to use relies on the presence of thead and tbody. That said, it doesn't seem to work correctly in all cases for me either, for different (presumably?!) reasons. I'll give a few other libraries a try instead...

**Comment by jcb91** [comment]
OK, so Mottie's tablesorter seems to work ok on the R-generated table, despite the missing heading/th column.

The reloading being different to running was down to the load time of the external library, which meant that the notebook.loaded callback was firing before the library loaded. I've added an extra `bootstrapify_all` call on library load to fix that (hopefully!)

**Comment by jcb91** [comment]
@juhasch any joy with the latest version?

**Comment by jcb91** [comment]
(rebased)

**Pull request merged**
