### PR TITLE
[livemdpreview] add new nbextension!

### PR DESCRIPTION
**Pull request by jcb91**
idea prompted from https://github.com/jupyter/notebook/issues/2882

### CODE REVIEW

**Comment by juhasch** [comment]
Very nice :smile:

One minor thing: The default for `show_side_by_side` is different in the yaml and in the js file.
I guess we should *really* try to read in the default values from the description file and not have it set twice.

**Comment by jcb91** [comment]
Ah, good spot @juhasch, thanks! 

> I guess we should really try to read in the default values from the description file and not have it set twice.

Haha yeah, it could be simpler! I think we'd need to be using JSON though :wink:

**Comment by juhasch** [comment]
If it works I will even swallow evil JSON :smirk:

**Comment by jcb91** [comment]
Haha, well, getting the defaults from json should be easy enough, something like

```js
var utils = require('base/js/utils');
var pkg_json_url = require.toUrl('./package.json');
var params = {};

utils.promising_ajax(
    pkg_json_url, {processData : false, cache : false, type : "GET", dataType : "json"}
).then(function (pkg_json) {
    // e.g. if we use the config suggested in https://github.com/jupyter/notebook/issues/2824#issuecomment-334124949
    $.extend(true,
        params,
        pkg_json.org_jupyter_nbextension,
        Jupyter.notebook.config.data.mynbextensionname);
});
```

**Comment by jcb91** [comment]
hmm, actually, I guess it's a bit more difficult, since there's also the stored parameter metadata. So you'd need something like

```js
var default_params = {};
pkg_json.org_jupyter_nbextension.parameters.forEach(
    function (param) { default_params[param.name] = param.default; });
```

to handle that

**Pull request merged**
