### PR TITLE
Cell filter extension

### PR DESCRIPTION
**Pull request by benelot**
I finally finished my second extension. Filter by tags in the notebook section. Thanks for the inputs in #1214, the disabling of the keyboard shortcuts basically made it work for the first time.

### CODE REVIEW

**Comment by benelot** [comment]
I just realized I forgot to hide outputs! Well. I am going to add that soon.

**Comment by benelot** [comment]
I will test some more if I find problems. Then it should be good to go.

**Comment by jcb91** [comment]
This looks good to me, although it won't play well with collapsible headings as it is at the moment. That's ok though, a separate PR some other time can get them working nicely together. Could you add a note to the github master section of the changelog about the new addition? Thanks :)

**Comment by benelot** [comment]
Oh right, I forgot the changelog again. Will do it soon.

I realized the issue with collapsible headings and some other extensions that show additional features, but I did not know how to handle them and be safe if they are not enabled. Let us check that in a separate PR.

**Comment by benelot** [comment]
Done! Ready to pull.

**Comment by juhasch** [comment]
Looks good to me. The appveyor error looks unrelated.

**Comment by syagev** [comment]
@benelot this extension seems very useful to me, but where is the mentioned "search bar"? I can't find it 😳...

image

**Comment by benelot** [comment]
@syagev Happy to hear my extension could be useful to you. The search bar should be added to the maintoolbae container at the top.

```
var form = $('<form/>')                                                                                     // insert a form into the main toolbar container
            .css('padding', '0 7px 4px')
            .appendTo('#maintoolbar-container');
```

Maybe they renamed that and the extension broke? Not sure. The searchbox should be all to the right in the same toolbar as the Run button and the Code Dropdown. If you are familiar with the developer tools of your browser, you could quickly check if the toolbar still has the same ID.

**Comment by syagev** [comment]
Thanks for the reply @benelot, I took a look at the console as suggested and opened a ticket - https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1542

**Pull request merged**
