### PR TITLE
[toc2] Add a parameter to enable/disable cell widening

### PR DESCRIPTION
**Pull request by jfbercher**
This addresses #871. 
A parameter is added to enable/disable cell widening to fit the browser window (parameter is set to false to be consistent with the previous behavior). This works independently of the state of the toc display (sidebar/floating/hidden). Loading of config parameters have been a bit cleaned. Also reworked the code so that everything (I hope)  resizes correctly with the main browser window.

### CODE REVIEW

**Comment by jcb91** [comment]
looks like a good plan to me, but I'll leave merging for to you, for when you're happy with it @jfbercher :)

**Comment by jat255** [comment]
Even when disabling the new widen option, I find that the top menu items and the body of the notebook are still widened. The menu bar takes up the full width, and the body cells now take up 82% of the width (compared to a fixed 1140px width without it). I would like to use this extension, but on my widescreen monitor it is difficult to read at full (or 82% width). Is it feasible to completely disable the width scaling, but keep the ToC feature? 

In my opinion, the docking is nice, but a Table of Contents extension should not completely reformat the whole page. I had to selectively disable all of my extensions to figure out which one was the culprit, and I definitely did not expect it to be this one!

Otherwise, I very much like this extension 😄

**Comment by jfbercher** [comment]
I am not sure to understand well. For the menu & menubar, you can disable moving on the left by disabling the parameter "Move notebook's title and menu on the left instead of being centered". This feature was recommended/requested by others users. As for the 82% width, I used it to look like the default; isn't it the case? Anyway we could let it configurable.

**Comment by jat255** [comment]
You're right about the menu bar. I simply missed that option. All is well when it is unchecked.

As for the width, I would agree that configurable would be the most versatile and satisfy the majority of users. I have a fairly wide monitor (1920px), so my 82% is probably wider than someone on a 1600 or 1200px screen.

**Comment by jcb91** [comment]
I think the default is actually fixed at several steps (the standard bootstrap small/medium/large screen stops), rather than a percentage...

**Comment by jfbercher** [comment]
@jcb91 I don't know all that, but it seems indeed that the best is to reset the width by a `.css({'width': ""})` to return to the default behavior. I will update that.

**Pull request merged**
