### PR TITLE
Remove OSX travis run

### PR DESCRIPTION
**Pull request by juhasch**

### CODE REVIEW

**Comment by jcb91** [comment]
:+1:

**Comment by josephcslater** [comment]
Does this mean there will no longer be OSX support?

**Comment by jcb91** [comment]
> Does this mean there will no longer be OSX support?

No, OSX is similar enough to linux that the CI builds there are pretty much sufficient.

The main issue here was that our OSX Travis runs were slow to start, and were running into problems with the initial python setup, which was causing PRs to look like they had breaking changes all the time, when in reality they didn't. Since we don't have object libraries, and most of our file-location stuff is handled by `jupyter_core`, we don't have much in the way of platform-dependent code anyway. However, it would be nice to re-add OSX runs eventually, even if only for the added peace of mind.

Hope that makes sense?

**Comment by josephcslater** [comment]
Perfect. As you know from my recent issue... I have one that I can't trace and am hoping it's figured out eventually (or my system inexplicably continues to work).

**Pull request merged**
