### PR TITLE
Make RTD build work

### PR DESCRIPTION
**Pull request by juhasch**

### CODE REVIEW

**Comment by jcb91** [comment]
looks like a good plan to me!

**Comment by juhasch** [comment]
Year, we got docs now :smile:
http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/

**Comment by juhasch** [comment]
Well, not quite. The extension descriptions are not included. It just would have been too easy...

**Comment by jcb91** [comment]
haha too true! By the way, do we actually need to convert everything to rst? Since sphinx semms to support markdown docs directly, and we're writing in markdown to begin with, so not using any rst-only features, it seems like it might be possible to skip...

**Comment by juhasch** [comment]
I would love to skip this step. Although sphinx supports md, I did not find a good way because:
a) you can't easily access the source code directories, especially on Windows. 
b) images don't work is you give sphinx md files.

**Comment by jcb91** [comment]
> you can't easily access the source code directories, especially on Windows (i.e no symlinks). 

Sure, but we could simply copy to a temporary build directory without conversion

> images don't work is you give sphinx md files.

Ah, that is a bit of a deal-breaker...

**Comment by juhasch** [comment]
Now I got it working for my local repo:
http://juhasch-jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html

I just need to do a little cleanup and it should be fine now. 
Actually recommonmark is set up for sphinx, so I might try it again so the pandoc step is no longer required.

**Comment by jcb91** [comment]
ah, nice :sunglasses: 
Some of the top-level headings in the per-extension readmes need a little tweaking though, it seems. E.g, the headings for the latex_envs section `Demo/documentation` appears in the sidebar as though it's an extension itself (see http://juhasch-jupyter-contrib-nbextensions.readthedocs.io/en/latest/latex_envs/readme.html#demo-documentation)

Sterling work though :smile: :+1:

**Comment by juhasch** [comment]
Yes, a few changes are still needed. I already changed most of the readme files and only skipped the ones with open PRs (at that time).

Unfortunately, it is difficult to generate PDF docs or similar. Hard to embed animated GIFs there...

**Comment by jfbercher** [comment]
Very nice work @juhasch !

**Pull request merged**
