### PR TITLE
Fix html_embed exporter

### PR DESCRIPTION
**Pull request by juhasch**
Fixes issue #1041:
Correctly embed images already embedded in the notebook itself.

### CODE REVIEW

**Comment by gabyx** [comment]
was the path already in the metadata?
I thought there is not `path` variable in the resource metadata :-)
if so, this is a cool fix :-) fixes my export button top

**Comment by juhasch** [comment]
This works at when calling nbconvert from command line.
I don't have notebook 5.1 running, so this might not work with your extension. However, I would assume this is a bug in the notebook then.

**Comment by gabyx** [comment]
ah, ok, hm..., so this merge will 
make my extension not working before the notebook bug is not resolved...
maybe I have some time

**Comment by juhasch** [comment]
Hmm, looks like the notebook calls `from_notebook_node()` and does not provide the path. In my eyes it should. This means I need to add a check in the exporter, and your problem with the extension is still not solved.

**Comment by gabyx** [comment]
Created a pull request to fix that:
 https://github.com/jupyter/notebook/pull/2753

**Pull request merged**
