### PR TITLE
Test/embeddingtests

### PR DESCRIPTION
**Pull request by juhasch**
This is just for testing the appveyor test failures.

### CODE REVIEW

**Comment by jcb91** [comment]
I've something similar in my lxml branch...

**Comment by jcb91** [comment]
It seems that part of the problem is that the lxml conversion converts the `&#39;` codes into regular apostrophe characters, and eats some whitespace (at least in 2.7)...

**Comment by juhasch** [comment]
I can produce it locally now (wrong exporter was called before).
Stdout no embedding:
```
[NbConvertApp] Converting notebook notebook.ipynb to html
[NbConvertApp] Writing 249492 bytes to notebook.html
```
Stdout embedding:
```
[NbConvertApp] Converting notebook notebook.ipynb to html_embed
[NbConvertApp] try embedding url: D:\src\jupyter_contrib_nbextensions\tests\data\icon.png, format: png
[NbConvertApp] Writing 249544 bytes to notebook.html
```

In test_exporter:
```
statinfo_e.st_size = 249544
statinfo.st_size = 261295
```
Why is the not-embedded filesize larger than nbconvert reports it to be ?

**Comment by juhasch** [comment]
Not embedded HTML file start:
```
<!DOCTYPE html>
<html>
<head><meta charset="utf-8" />
```

Embedded HTML file start:
```
<html>
<head><meta charset="utf-8">
```

OK, our test is not good enough.

**Comment by jcb91** [comment]
> Why is the not-embedded filesize larger than nbconvert reports it to be ?

😕 not sure... maybe this is a timing issue?

**Comment by juhasch** [comment]
The size difference is due to LF vs. CR+LF.

**Comment by jcb91** [comment]
> The size difference is due to LF vs. CR+LF.

Oh man! That's still a problem 😓

**Comment by jcb91** [comment]
Perhaps we ought to read the files and strip CRs then

**Comment by juhasch** [comment]
We could parse nbconvert stdout. However, I don't understand why nbconvert gives back a different file size in the embedding case. Strange.

**Comment by jcb91** [comment]
> However, I don't understand why nbconvert gives back a different file size in the embedding case. Strange.

Possibly lxml has already added line endings?

**Comment by juhasch** [comment]
The thing is, that nbconvert reports the correct number. So it seems to not count the additional CR.
I guess the best way is to create a helper function that calculates the file size minus CR.

**Comment by juhasch** [comment]
😄 Works now!

**Comment by jcb91** [comment]
> The thing is, that nbconvert reports the correct number. So it seems to not count the additional CR.

maybe it counts each line separately?

It might be simpler (better?!) To do a `'\n'.join(output.splitlines())` in the exporter, rather than hack the test. It seems to me better to avoid creating the CAR in the first place, no?

**Comment by juhasch** [comment]
Good point.

OK, I guess the right thing to do is call
`embedded_output = et.tostring(root, method="html", encoding='unicode')`
instead of 
`embedded_output = et.tostring(root, method="html")`

in the exporter.

**Comment by gabyx** [comment]
I added: embedded_output = et.tostring(root.getroottree(), method="html", encoding='unicode')

**Pull request closed without merging**
