### PR TITLE
=Added the 'addbefore' extenstion'

### PR DESCRIPTION
**Pull request by oxinabox**
I created this extention to bring back the "create cell before" functionality of IPython 1

Based on my old work for http://stackoverflow.com/questions/23577208/ipython-2-0-notebook-where-has-the-add-cell-above-button-gone-and-how-do-i-g

### CODE REVIEW

**Comment by juhasch** [comment]
Thank you, sounds reasonable. Can you add a little description for those who don't remember IPython 1 ?

**Comment by oxinabox** [comment]
Do you want a more description here, or editted in?

It is the same as going into the "Insert" menu, and clicking "Insert Cell Above",

**Comment by jcb91** [comment]
@oxinabox Apologies for the delay looking at this. If you'd still like this added, it'll need a bit of updating since the repo restructuring. Essentially:

1. nbextensions now live as subdirectories of [`src/jupyter_contrib_nbextensions/nbextensions`](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/9c22edb6447b1bdfaf3c486af0d327e43c6d444c/src/jupyter_contrib_nbextensions/nbextensions)
2. yes, add the description into the `readme.md` file.

Thanks!

**Comment by oxinabox** [comment]
yeah, still interesting in having it merged.
Some time in the next month or so I'll fix it up.

**Pull request closed without merging**
